services:
    db:
        image: postgres:latest
        environment:
            POSTGRES_DB: django-expense
            POSTGRES_USER: root
            POSTGRES_PASSWORD: root
        ports:
            - "8001:5432"

volumes:
    db_data:
        driver: local
