# Generated by Django 5.2.7 on 2025-10-30 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='family',
            name='currency',
            field=models.CharField(default='HKD', max_length=10),
        ),
        migrations.AddField(
            model_name='family',
            name='max_budget',
            field=models.FloatField(default=0),
        ),
    ]
