# Generated by Django 5.2.7 on 2025-10-30 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0004_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='category',
            field=models.CharField(blank=True, choices=[('food', 'Food'), ('transport', 'Transport'), ('entertainment', 'Entertainment'), ('shopping', 'Shopping'), ('other', 'Other'), ('rent', 'Rent'), ('utilities', 'Utilities'), ('insurance', 'Insurance'), ('education', 'Education'), ('health', 'Health')], max_length=100),
        ),
    ]
