# Generated by Django 5.2.7 on 2025-12-24 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0008_qrcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrcode',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
